#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Remove files
rm -rf 0
#restore0Dir
rm -rf processor*
rm -rf postProcessing
rm log.setFields
rm log.renumberMesh*
rm log.decomposePar*
rm log.interFoam*
rm log.reconstructPar
rm -rf logs
rm Parameters.*

#------------------------------------------------------------------------------
