#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions

# To allow OpenMPI to run as root
export OMPI_ALLOW_RUN_AS_ROOT=1
export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
#------------------------------------------------------------------------------#
# create foam file for Paraview
touch case.foam
#------------------------------------------------------------------------------#

### PART 1: GEOMETRY ###
# ./AllrunGeo

# Copy hull surface from resources folder
mkdir -p constant/triSurface
cp geometry/hull.stl constant/triSurface/

# # Pre Trim and Sinkage
# runApplication surfaceTransformPoints \
#     -translate '(0 0 0.02)' \
#     -rollPitchYaw '(0 -3 0)' \
#     constant/triSurface/hull.stl \
#     constant/triSurface/hull.stl

### PART 2: MESH ###
# Generate hull.eMesh file (edge features)
runApplication surfaceFeatureExtract

runApplication blockMesh

# Define the number of refinement iterations
N_ITERATIONS=4
# Define the transition point for 3D refinement
TRANSITION_3D=5
for i in $(seq 1 $N_ITERATIONS)
do
    if [ $i -lt $TRANSITION_3D ]; then
        # Use 2D(x,y) refinement for iterations before transition point
        runApplication -s $i \
            foamDictionary  system/refineMeshDict -entry set -set c${i}

        runApplication -s $i \
            topoSet -dict system/topoSetDict

        runApplication -s $i \
            refineMesh -dict system/refineMeshDict -overwrite
    else
        # Use 3D refinement for iterations after and including transition point
        runApplication -s $i \
            foamDictionary  system/refineMeshDict3D -entry set -set c${i}

        runApplication -s $i \
            topoSet -dict system/topoSetDict

        runApplication -s $i \
            refineMesh -dict system/refineMeshDict3D -overwrite
    fi
done

runApplication -s beforeSnappy checkMesh -allGeometry -allTopology

runApplication -s forSnappyHexMesh decomposePar
runParallel snappyHexMesh -overwrite
runParallel redistributePar -reconstruct -constant -overwrite
rm -rf processor* # clean decomposed mesh not to interfere with interFoam decomposition

runApplication checkMesh -allGeometry -allTopology -writeAllFields -writeSets vtk -writeChecks json

# # for ParaView mesh quality visualization
runApplication setsToZones -noFlipMap -time 3

# ./AllCreateParametersFiles
#------------------------------------------------------------------------------
