#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions

# To allow OpenMPI to run as root
export OMPI_ALLOW_RUN_AS_ROOT=1
export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
#------------------------------------------------------------------------------

### PART 3: SOLVER ###
./AllCreateParametersFiles

restore0Dir

runApplication setFields

runApplication decomposePar

runParallel renumberMesh -overwrite

runParallel $(getApplication)

runApplication reconstructPar

runApplication -s yPlus interFoam -postProcess -func yPlus
#------------------------------------------------------------------------------
