#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions

# To allow OpenMPI to run as root
export OMPI_ALLOW_RUN_AS_ROOT=1
export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
#------------------------------------------------------------------------------#
# create foam file for Paraview
touch case.foam
#------------------------------------------------------------------------------#

# ./AllrunGeo

# Copy hull surface from resources folder
mkdir -p constant/triSurface
cp geometry/hull.stl constant/triSurface/

# Generate hull.eMesh file (edge features)
runApplication surfaceFeatureExtract

runApplication blockMesh # z-dir refinement

# Refinement in x and y dir only
for i in 1 2 3 4 5 #6
do
    runApplication -s $i \
        foamDictionary  system/refineMeshDict -entry set -set c${i}

    runApplication -s $i \
        topoSet -dict system/topoSetDict

    runApplication -s $i \
        refineMesh -dict system/refineMeshDict -overwrite
done

# Refinement in all 3 directions
for i in 6
do
    runApplication -s $i \
        foamDictionary  system/refineMeshDict3D -entry set -set c${i}

    runApplication -s $i \
        topoSet -dict system/topoSetDict

    runApplication -s $i \
        refineMesh -dict system/refineMeshDict3D -overwrite
done

runApplication -s beforeSnappy checkMesh -allGeometry -allTopology

runApplication -s forSnappyHexMesh decomposePar # decompose to run snappyHexMesh in parallel
runParallel snappyHexMesh -overwrite

runParallel redistributePar -reconstruct -constant -overwrite # (not work in OF10)

rm -rf processor* # clean decomposed mesh not to interfere with interFoam decomposition

runApplication checkMesh -allGeometry -allTopology -writeAllFields -writeSets vtk -writeChecks json

# # for ParaView mesh quality visualization
runApplication setsToZones -noFlipMap -time 3 # windows ParaView reader cannot load sets, therefore first convert sets to zones

# ./AllCreateParametersFiles
#------------------------------------------------------------------------------
