#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory

# Create variables
# hull="geometry/w3_orig.stl" # preprocessed watertight solid hull
# draft=0.108 # 0.0928 for ori
# rho_water=997
# pre_trim_angle=3.485 # [deg] positive angle --> bow up
# pre_sinkage=0.045 # [m] model scale sinkage -ve --> sinkage (downward)
# scale_factor=10

# hull="geometry/hullDTC.stl" # preprocessed watertight solid hull
# draft=0.244 
# rho_water=998

# hull="geometry/kcs_SB.stl" # preprocessed watertight solid hull
# draft=0.3418 
# rho_water=998

hull="geometry/hull.stl" # preprocessed watertight solid hull
draft=0.3 
rho_water=998

# hull="geometry/hull_surface.stl" # preprocessed watertight solid hull
# draft=100 
# rho_water=998

# hull="geometry/jbc_closed_FreeCAD.stl" # preprocessed watertight solid hull
# draft=400 
# rho_water=998
# scale_factor=0.001

# hull="geometry/kcs_closed_FreeCAD.stl" # preprocessed watertight solid hull
# draft=10.8
# rho_water=998
# scale_factor=$(echo "1/31.599" | bc -l)


python3 utilities/blenderHullProperties.py $hull --draft $draft --rho_water $rho_water
# python3 utilities/blenderHullProperties.py $hull --draft $draft --rho_water $rho_water --scale $scale_factor --move_origin
# python3 utilities/blenderHullProperties.py $hull --draft $draft --rho_water $rho_water --trim_angle $pre_trim_angle --sinkage $pre_sinkage --scale $scale_factor
# python3 utilities/blenderHullProperties.py $hull --draft $draft --rho_water $rho_water --trim_angle $pre_trim_angle --sinkage $pre_sinkage --CoG 0.586 0 0.156

# Copy hull surface from resources folder
mkdir -p constant/triSurface
cp geometry/hull.stl constant/triSurface/

#------------------------------------------------------------------------------
# sudo update-alternatives --config python3

# python3 utilities/blenderHullProperties.py "geometry/hull.stl" --draft 0.3 --rho_water 1000